server:
  servlet:
    context-path: /jf/cache
spring:
  rabbitmq:
    host: 192.168.1.28
    username: guest
    password: guest
    port: 5672
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
  redis:
    database: 0
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-idle: 8 # 连接池中的最大空闲连接 默认 8
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        min-idle: 0 # 连接池中的最小空闲连接 默认 0
    cluster:
      max-redirects: 3
      nodes: 
      - 192.168.1.28:7000
      - 192.168.1.28:7001
      - 192.168.1.28:7002
      - 192.168.1.28:7003 
      - 192.168.1.28:7004
      - 192.168.1.28:7005
    timeout: 60000
#    sentinel:
#      master: sentinel-master
#      nodes:
#      - 192.168.1.28:26479
#      - 192.168.1.28:26480
#      - 192.168.1.28:26481
file:
  path:
    linux: /midware/file_temp
    windows: F:/file_temp
